### ISSUE TITLE
refactor(design): update the WP.org plugin thumb and banner

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Yelp-Widget-Pro#8]
## Issue Overview

The free plugin's thumbnail and banner are outdated and should be updated to a more modern look 
and also incorporate the new WPBR branding if possible.

- [x] Design new thumbnail
- [x] Design new banner
- [x] Implement on release

## Current Visual

![2018-08-09_15-07-58](https://user-images.githubusercontent.com/1571635/43928514-0520cdd2-9be6-11e8-94fe-260937947753.png)

**Comment by DevinWalker** [comment]
I wanted to tie in our new WPBR brand to the design of the banner and thumb. Feedback welcomed.

## Plugin Banner

![plugin-banner-2018](https://user-images.githubusercontent.com/1571635/44366498-b9d0b780-a481-11e8-9aa8-6f42bf26c56b.jpg)

## Plugin Thumb

![plugin-thumb-2018](https://user-images.githubusercontent.com/1571635/44367211-f4d3ea80-a483-11e8-82df-365d7f8c34e4.jpg)

**Comment by mathetos** [comment]
I like it a lot. The Yelp Stars underneath look a little weak though... Also the font for "Developed By" is too thin, almost not even visible. Other than that, ship it!

**Comment by DevinWalker** [comment]
@mathetos I dropped the "Developed by" text and increased the star size.

**Comment by kevinwhoffman** [comment]
I like it overall.

`Yelp Widget Pro` text looks too chunky. `Roboto Bold` is the font face we've been using across the site for headings. What you have above looks like `Robot Black`.

Also make sure to use the Yelp stars from https://www.yelp.com/developers/display_requirements

**Comment by DevinWalker** [comment]
I updated the text and made sure the stars are the same as the requirements.
